-- Auth/RBAC foundation for the Foosball-MMR admin surface.
--
-- Apply with:
--   npx supabase db push
--
-- After this migration, bootstrap the first sysadmin manually from the SQL
-- editor or psql. See the notes at the end of this file.

create table if not exists public.app_state (
  id integer primary key,
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.app_state
  add column if not exists updated_at timestamptz not null default now();

insert into public.app_state (id, state)
values (1, '{}'::jsonb)
on conflict (id) do nothing;

create table if not exists public.app_state_history (
  id bigint generated by default as identity primary key,
  state jsonb not null,
  saved_at timestamptz not null default now()
);

alter table public.app_state_history
  add column if not exists saved_at timestamptz not null default now();

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('referee', 'gameadmin', 'sysadmin')),
  call_sign text not null unique,
  active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  actor_call_sign text,
  actor_role text,
  action text not null,
  target_type text,
  target_id text,
  details jsonb,
  created_at timestamptz not null default now()
);

create index if not exists profiles_role_active_idx
  on public.profiles (role, active);

create index if not exists audit_log_created_at_idx
  on public.audit_log (created_at desc);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at
before update on public.profiles
for each row execute function public.touch_updated_at();

drop trigger if exists app_state_touch_updated_at on public.app_state;
create trigger app_state_touch_updated_at
before update on public.app_state
for each row execute function public.touch_updated_at();

create or replace function public.role_rank(role_name text)
returns integer
language sql
immutable
as $$
  select case role_name
    when 'referee' then 1
    when 'gameadmin' then 2
    when 'sysadmin' then 3
    else 0
  end;
$$;

create or replace function public.has_admin_role(required_role text default 'referee')
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.user_id = auth.uid()
      and p.active = true
      and public.role_rank(p.role::text) >= public.role_rank(required_role)
  );
$$;

create or replace function public.log_audit_event(
  p_action text,
  p_target_type text default null,
  p_target_id text default null,
  p_details jsonb default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  actor public.profiles%rowtype;
begin
  select *
    into actor
  from public.profiles
  where user_id = auth.uid()
    and active = true;

  if actor.user_id is null then
    raise exception 'Only an active admin can write audit events';
  end if;

  insert into public.audit_log (
    actor_user_id,
    actor_call_sign,
    actor_role,
    action,
    target_type,
    target_id,
    details
  )
  values (
    actor.user_id,
    actor.call_sign,
    actor.role,
    p_action,
    p_target_type,
    p_target_id,
    p_details
  );
end;
$$;

create or replace function public.update_state_versioned(
  expected_v integer,
  new_state jsonb
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  current_state jsonb;
  current_v integer;
begin
  if not public.has_admin_role('referee') then
    raise exception 'Only an active admin can update app state';
  end if;

  select state
    into current_state
  from public.app_state
  where id = 1
  for update;

  if current_state is null then
    current_v := 0;
    if coalesce(expected_v, 0) <> 0 then
      return false;
    end if;

    insert into public.app_state (id, state)
    values (1, new_state);
  else
    current_v := coalesce((current_state->>'_v')::integer, 0);
    if current_v <> expected_v then
      return false;
    end if;

    update public.app_state
    set state = new_state
    where id = 1;
  end if;

  perform public.log_audit_event(
    'update_state',
    'app_state',
    '1',
    jsonb_build_object(
      'expected_v', expected_v,
      'new_v', coalesce((new_state->>'_v')::integer, null)
    )
  );

  return true;
end;
$$;

create or replace function public.replace_state_admin(
  new_state jsonb,
  p_action text default 'replace_state'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  current_state jsonb;
  current_v integer;
  next_state jsonb;
begin
  if not public.has_admin_role('sysadmin') then
    raise exception 'Only an active sysadmin can replace app state';
  end if;

  select state
    into current_state
  from public.app_state
  where id = 1
  for update;

  current_v := coalesce((current_state->>'_v')::integer, 0);
  next_state := jsonb_set(
    coalesce(new_state, '{}'::jsonb),
    '{_v}',
    to_jsonb(current_v + 1),
    true
  );

  next_state := jsonb_set(
    next_state,
    '{_meta}',
    coalesce(next_state->'_meta', '{}'::jsonb) ||
      jsonb_build_object(
        'lastWriteAt', now(),
        'lastWriterId', auth.uid(),
        'lastWriteAction', p_action
      ),
    true
  );

  insert into public.app_state (id, state)
  values (1, next_state)
  on conflict (id) do update
    set state = excluded.state;

  perform public.log_audit_event(
    p_action,
    'app_state',
    '1',
    jsonb_build_object('new_v', current_v + 1)
  );

  return next_state;
end;
$$;

alter table public.app_state enable row level security;
alter table public.app_state_history enable row level security;
alter table public.profiles enable row level security;
alter table public.audit_log enable row level security;

drop policy if exists "Public can read current app state" on public.app_state;
create policy "Public can read current app state"
on public.app_state
for select
to anon, authenticated
using (true);

drop policy if exists "Admins can read app state history" on public.app_state_history;
create policy "Admins can read app state history"
on public.app_state_history
for select
to authenticated
using (public.has_admin_role('referee'));

drop policy if exists "Admins can create app state history" on public.app_state_history;
create policy "Admins can create app state history"
on public.app_state_history
for insert
to authenticated
with check (public.has_admin_role('referee'));

drop policy if exists "Sysadmins can prune app state history" on public.app_state_history;
create policy "Sysadmins can prune app state history"
on public.app_state_history
for delete
to authenticated
using (public.has_admin_role('sysadmin'));

drop policy if exists "Admins can read own profile" on public.profiles;
create policy "Admins can read own profile"
on public.profiles
for select
to authenticated
using (user_id = auth.uid() and active = true);

drop policy if exists "Sysadmins can read all profiles" on public.profiles;
create policy "Sysadmins can read all profiles"
on public.profiles
for select
to authenticated
using (public.has_admin_role('sysadmin'));

drop policy if exists "Sysadmins can update profiles" on public.profiles;
create policy "Sysadmins can update profiles"
on public.profiles
for update
to authenticated
using (public.has_admin_role('sysadmin'))
with check (public.has_admin_role('sysadmin'));

drop policy if exists "Admins can read audit log" on public.audit_log;
create policy "Admins can read audit log"
on public.audit_log
for select
to authenticated
using (public.has_admin_role('referee'));

grant usage on schema public to anon, authenticated;
grant select on public.app_state to anon, authenticated;
grant select on public.profiles to authenticated;
grant select on public.audit_log to authenticated;
grant select, insert on public.app_state_history to authenticated;
grant delete on public.app_state_history to authenticated;
grant execute on function public.has_admin_role(text) to authenticated;
grant execute on function public.log_audit_event(text, text, text, jsonb) to authenticated;
grant execute on function public.update_state_versioned(integer, jsonb) to authenticated;
grant execute on function public.replace_state_admin(jsonb, text) to authenticated;

-- First sysadmin bootstrap:
--
-- 1. Create one Supabase Auth user with the same passphrase-to-email convention
--    used by src/authClient.js. A quick browser console helper after opening the
--    deployed app:
--
--      const passphrase = "your chosen first passphrase";
--      const bytes = new TextEncoder().encode(passphrase);
--      const digest = await crypto.subtle.digest("SHA-256", bytes);
--      const hash = Array.from(new Uint8Array(digest)).map(b => b.toString(16).padStart(2, "0")).join("");
--      `${hash.slice(0, 24)}@internal.foosballmmr.local`;
--
-- 2. In Supabase Dashboard > Authentication > Users, create a confirmed user
--    with that synthetic email and the same passphrase as its password.
--
-- 3. Insert the matching profile row:
--
--      insert into public.profiles (user_id, role, call_sign, active)
--      values ('<auth.users.id>', 'sysadmin', 'first-sysadmin', true);
--
-- After this, log in through the app with only the passphrase, open the Logins
-- admin tab, and generate all future accounts from there.
